#!/bin/bash

case $BLOCK_BUTTON in
	1) setsid -f "$TERMINAL" -e pulsemixer ;;
	2) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
	3) pgrep -x dunst >/dev/null && notify-send " Volume module" "\- Shows volume ,  if muted.
- Middle click to mute.
- Scroll to change."
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "<span color='#cc241d'></span>\\n" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

# if [ "$vol" -gt "70" ]; then
# 	icon="<span color='#458588'></span>"
# elif [ "$vol" -lt "30" ]; then
# 	icon="<span color='#458588'></span>"
# else
# 	icon="<span color='#458588'></span>"
# fi

if [ "$vol" -gt "70" ]; then
	color="#458588"
elif [ "$vol" -lt "30" ]; then
	color="#458588"
else
	color="#458588"
fi

printf "%s %s%%\\n" "$icon" "$vol"


# printf "    <span color='%s'>%s </span>\n" "$color" "$vol" 
# printf "  %s\n" "$vol" 
# RED="\e[0;31m"
# GREEN="\e[0;32m"
# RESET="\e[0m"

# printf "%s $RED%s $GREEN%s $RESET%s\n" BLACK RED GREEN BLACK